language: go

go: 1.14

branches:
  only:
    - master
    - /^v.*$/

before_install:
  - env GO111MODULE=off go get github.com/mattn/goveralls
  - curl -sfL https://install.goreleaser.com/github.com/golangci/golangci-lint.sh | sh -s -- -b $(go env GOPATH)/bin v1.23.8
  - env GO111MODULE=on go mod download

script:
  - make test
  - make build
  - make lint

after_success:
  - make goveralls

deploy:
- provider: script
  skip_cleanup: true
  script: curl -sL https://git.io/goreleaser | bash
  on:
    tags: true
    condition: $TRAVIS_OS_NAME = linux
